kind: pipeline
name: default

workspace:
  base: /go
#  path: src/github.com/cuisongliu/githubio

steps:
  - name: submodules
    image: docker:git
    commands:
      - git clone --recursive https://github.com/cuisongliu/githubio.git
  - name: build-hugo
    image: golang:1.11
    commands:
      - cd /go/githubio
      - go get -u github.com/gohugoio/hugo
      - hugo  -t hugo-tranquilpeak-theme
      - cd dist && rm -rf *
      - cp -rf ../public/* .
      - git config --global user.email "drone@cuisongliu.com"
      - git config --global user.name "drone"
      - git add .
      - git commit -am "auto shell commit by hugo for drone"
  - name: publish
    image: plugins/gh-pages
    settings:
      username:
        from_secret: github_username
      password:
        from_secret: github_password
      pages_directory: dist/
