kind: pipeline
name: default

workspace:
  base: /go
#  path: src/github.com/cuisongliu/githubio

steps:
  - name: submodules
    image: docker:git
    commands:
      - git clone --recursive https://github.com/cuisongliu/githubio.git
  - name: build-hugo
    image: golang:1.13
    settings:
      username:
        from_secret: github_username
      password:
        from_secret: github_password
    commands:
      - cd /go && git clone https://github.com/gohugoio/hugo.git && cd hugo && go install
      - cd /go/githubio
      - hugo  -t hugo-tranquilpeak-theme
      - git clone https://github.com/cuisongliu/cuisongliu.github.io.git
      - cd cuisongliu.github.io && rm -rf *
      - cp -rf ../public/* .
      - git config --global user.email "drone@cuisongliu.com"
      - git config --global user.name "drone"
      - git add .
      - git commit -am "auto shell commit by hugo for drone"
      - echo "https://$PLUGIN_USERNAME:$PLUGIN_PASSWORD@github.com" >>  ~/.git-credentials
      - git config --global credential.helper store
      - git push   origin master

