kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/cuisongliu/githubio

clone:
  depth: 50

steps:
  - name: submodules
    image: docker:git
    commands:
      - git submodule update --recursive --remote
  - name: build-hugo
    image: golang:1.11
    commands:
      - ls -l themes/hugo-tranquilpeak-theme
      - go get -u github.com/gohugoio/hugo
      - hugo   -t hugo-tranquilpeak-theme
  - name: publish
    image: plugins/gh-pages
    commands:
      - ls -l dist
      - ls -l
