kind: pipeline
name: default


steps:
- name: build-font
  image: golang:1.10.8
  commands:
    - go get -u github.com/gohugoio/hugo
    - cd themes
    - git clone https://github.com/kakawait/hugo-tranquilpeak-theme.git
    - cd ../
    - hugo  -t hugo-tranquilpeak-theme
    - git clone https://github.com/cuisongliu/cuisongliu.github.io
    - cd cuisongliu.github.io && rm -rf * && mv ../public/* .
    - ls -l
    - git config --global user.email "cuisongliu@qq.com"
    - git config --global user.name "drone"
    - git add . && git commit -am "commit from drone"
